### ISSUE TITLE
我尝试回答下：

### ISSUE THREAD

**Issue by monray357187** [brpc/media-server#3]
我尝试回答下：

1. 问题 1：有没有 bug？
iter_impl 出现 error 的时候，会调用 `set_error` ，阻止后续状态机的执行：

```cpp
    if (iter_impl.has_error()) {
        set_error(iter_impl.error());
        iter_impl.run_the_rest_closure_with_error();
    }
```

`do_commit` 的时候会判断 fsm_caller 当前是否处于 `error` 状态：

```cpp
void FSMCaller::do_committed(int64_t committed_index) {
    if (!_error.status().ok()) {
        return;
    }
```

FSMCaller 的  `set_error` 还会通知到 state machine 的 `on_error` 方法，表示一个不可恢复的错误发生，需要人工介入处理。整个状态机将停止，因此不会有后续的数据安全问题。并且需要强调 `_last_applied_index` 是内存状态， do_commit 最终存储的还是上一次的 index: 

```cpp
    int64_t last_applied_index = _last_applied_index.load(
                                        butil::memory_order_relaxed);
     .....
    _log_manager->set_applied_id(last_applied_id);
```

因此并不存在数据安全问题。

2. 什么情况下会导致 iter_impl 出现 error ？

用户在 apply task 到状态机的时候可能遇到不可控的异常（比如网络或者文件磁盘沾满等 IO 问题），这种时候用户可以主动终止状态机继续执行，调用 `set_error_and_rollback` 方法回滚，人工介入处理，待错误恢复后继续执行状态机。

_Originally posted by @killme2008 in https://github.com/brpc/braft/issues/173#issuecomment-546608747_

**Comment by jamesge** [comment]
答错地方了。
