### ISSUE TITLE
cdn_merge_to的具体用法可以介绍下吗

### ISSUE THREAD

**Issue by xiaozhihong** [brpc/media-server#4]
如果有L0(边缘), L1(汇聚), L2(中心)
3种节点, 只需要L0 proxy_to L1 proxy_to L2, 便可以建一个分发网络
假设一个机房有20个L0, 这些L0的上层是同一个L1, 如果20个L0都向L1回源, 会有20份流量
我理解的cdn_merge_to, 应该角色上类似"机房代理", 也就是这个机房内的20个L0都向cdn_merge_to的节点回源, cdn_merge_to再向上层L1回源, 达到节省传输带宽的目的? 
是这么理解吗?

**Comment by jamesge** [comment]
就是这个意思，机房内回源以合并回源流量
